//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theold
    {
        public Theold()
        {
            this.Oldandchildren = new HashSet<Oldandchildren>();
        }
    
        public int id { get; set; }
        public Nullable<int> streetid { get; set; }
        public Nullable<int> neiborcommitteeid { get; set; }
        public string name { get; set; }
        public int old { get; set; }
        public string idcardnumber { get; set; }
        public string theaaddress { get; set; }
        public string contactway_1 { get; set; }
        public string contactway_2 { get; set; }
        public string contactway_3 { get; set; }
        public string theoldpassword { get; set; }
        public string landing_1 { get; set; }
        public string landing_2 { get; set; }
        public string landing_3 { get; set; }
    
        public virtual ICollection<Oldandchildren> Oldandchildren { get; set; }
    }
}
